namespace d100_TTRPG.Enums
{
    public enum Races
    {
        Aasimar = 1,
        Anurans = 2,
        Bear = 3,
        Faun = 4,
        Hare = 5,
        Shark = 6,
        Catfolk = 7,
        Dhampir = 8,
        Djinn = 9,
        MoonElf = 10,
        SunElf = 11,
        Melondi = 12,
        Gnoll = 13,
        Goblin = 14,
        Mithranite = 15,
        Nubian = 16,
        Oriental = 17,
        Thessian = 18,
        Zymen = 19,
        Ifrit = 20,
        Kitsune = 21,
        Kobold = 22,
        Atlanteans = 23,
        Merrow = 24,
        Monitori = 25,
        Orc = 26,
        Sylph = 27,
        Bull = 28,
        Cow = 29,
        Varruck = 30,
        Raptor = 31,
        Scavenger = 32,
        Tengu = 33,
        Werewolf = 34,
        Drake = 35,
        Dryad = 36,
        Gnome = 37,
        Nymph = 38,
        Pixie = 39,
        Hornet = 40,
        Jotun = 41,
        Lamia = 42,
        Nectarine = 43,
        Angel = 44,
        Cyclops = 45,
        Oni = 46,
        Succubus = 47,
        Sphinx = 48
    }
}
