namespace d100_TTRPG.Enums
{
    public enum Talents
    {
        AllOutAttack = 1,
        ArcaneScatter = 2,
        Archmage = 3,
        AssassinStrike = 4,
        BalefulDirge = 5,
        BerserkCharge = 6,
        Blademaster = 7,
        BlindFighting = 8,
        Bully = 9,
        Catfall = 10,
        CombatMaster = 11,
        CombatReflexes = 12,
        CombatSense = 13,
        Counterattack = 14,
        Crackshot = 15,
        CrushingBlow = 16,
        CunningInitiative = 17,
        Diehard = 18,
        Endurance = 19,
        FuriousAssault = 20,
        HammerBlow = 21,
        HardTarget = 22,
        Haste = 23,
        HighImpact = 24,
        ImprovedCombatManeuver = 25,
        IronJaw = 26,
        Leadership = 27,
        LightningAttack = 28,
        LightSleeper = 29,
        MagicProficiency = 30,
        Marksman = 31,
        Meditation = 32,
        Paranoia = 33,
        Permanency = 34,
        Polyglot = 35,
        PowerAttack = 36,
        PowerAttackGreater = 37,
        PreternaturalSpeed = 38,
        QuickDraw = 39,
        RapidReload = 40,
        Riposte = 41,
        SkillFocus = 42,
        SkillFocusGreater = 43,
        SpellFocus = 44,
        SpellFocusGreater = 45,
        Spellshot = 46,
        SpellPierce = 47,
        StreetFighting = 48,
        Subdue = 49,
        SwiftAttack = 50,
        Takedown = 51,
        Tenacity = 52,
        Toughness = 53,
        UnarmedMaster = 54,
        UnarmedWarrior = 55,
        Vigilance = 56,
        WeaponsExpertMelee = 57,
        WeaponsExpertRanged = 58,
        WeaponFocus = 59,
        WeaponProficiency = 60,
        WorldlyKnowledge = 61
    }

    public enum TalentChains
    {
        Minion = 1,
        PracticeDrills = 2,

        DoubleTeam = 3,

        DoubleSlice = 4,
        FollowUp = 5,
        Defense = 6,

        Bloodlust = 7,
        Power = 8
    }
}
